config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'books#index'

  resources :books do
    resources :printing_prices, shallow: true
    member do
      get 'show_pdf', format: :pdf
      get 'printing_prices_show', to: 'books#printing_prices_show', as: 'printing_prices_show'
    end
    collection do
      get 'printing_prices_index', to: 'books#printing_prices_index', as: 'printing_prices_index'
      get 'all', to: 'books#all', as: 'all'
    end
  end


  resources :kit_books do
    resources :items
  end
   # Registrar o controller search
   resources :search, controller: 'search', stimulus: './search_controller'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :kit_books, dependent: :destroy
  has_many :printing_prices, dependent: :destroy
  accepts_nested_attributes_for :printing_prices, allow_destroy: true

  has_one :cover
  has_one :miolo
  has_one :guarda
  include PgSearch::Model

  validates :title, :code, :selo, presence: true

  pg_search_scope :search_by_title_and_code,
  against: [ :title, :code ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # skip_before_action :authenticate_user!, only: :index
  before_action :authenticate_user!, only: [:new, :edit, :index]

  def index
    #@books = Book.all
    if params[:query]
      @books = Book.search_by_title_and_code(params[:query])
      else
        @books = []
    end
  end

  def all
    @books = Book.all
  end

  def printing_prices_show
    @book = Book.find(params[:id])
    @printing_prices = @book.printing_prices.all
  end

  def printing_prices_index
    @books = Book.all
    # @book = Book.find(params[:id])
    # @printing_prices = @book.printing_prices
  end

  def show
    @book = Book.find(params[:id])
  end

  def show_pdf
    @book = Book.find(params[:id])

    respond_to do |format|
      format.pdf do
        render pdf: "Checklist - #{@book.title}",
               template: 'books/show',
               layout: 'pdf_layout'
      end
    end
  end

  def new
    @book = Book.new
    @book.printing_prices.build # Isso cria uma instância de printing_prices para o livro
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
      render :new
    end
  end


  def edit
    @book = Book.find(params[:id])
    @book.printing_prices.build unless @book.printing_prices.present?
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to root_path, notice: 'Book was successfully destroyed.'
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :code, :pages, :tiragem, :selo, :delivery_date, :fitilho,
      :cabeceado, :pintura_lateral, :sticker, :encartes,
      :cover_type, :cover_format, :cover_paper, :cover_colors, :cover_finish,
      :miolo_format, :miolo_paper, :miolo_colors, :miolo_finish,
      :guarda_format, :guarda_paper, :guarda_colors, :guarda_finish,

      printing_prices_attributes: [:id, :quantity, :santa_marta_price, :pancron_price, :ipsis_price, :coan_price, :geografica_price, :leograf_price, :_destroy]
    )
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_budget_prices.html.erb
 <td><%= f.input :quantity, label: false %></td>
 <td><%= f.input :ipsis_price, label: false %></td>
 <td><%= f.input :coan_price, label: false %></td>
 <td><%= f.input :geografica_price, label: false %></td>
 <td><%= f.input :leograf_price, label: false %></td>
 <td><%= f.input :santa_marta_price, label: false %></td>
 <td><%= f.input :pancron_price, label: false %></td>

app/views/books/_show.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>CHECKLIST</title>
  <!-- Inclua os cabeçalhos e estilos necessários para a formatação do PDF aqui -->
  <style>

  h2 {
    text-align: end;
  }

  h3 {
    text-align: center;
  }

  .book-form-header {
    display: flex;
    text-align: center;
    justify-content: center;
    align-items: flex-end;
    margin-bottom: 24px;
   }

  .book-data {
    margin: 0 15%;
  }

  .book-data h3 {
    text-align: center;
    padding: 16px;
  }
</style>

</head>
<body>
 <div class="book-form-header">
    <%= image_tag wicked_pdf_asset_base64("logo_darkside_branca.png"), style: "width: 90px; margin-right: 24px;" %>
    <h2>CHECKLIST DE LANÇAMENTO</h2>
  </div>

  <div class="book-data">

    <h3>Dados Gerais</h3>
    <p><strong>Título:</strong> <%= @book.title.upcase %></p>
    <p><strong>Código:</strong> <%= @book.code %></p>
    <p><strong>Páginas:</strong> <%= @book.pages %></p>
    <p><strong>Tiragem:</strong> <%= @book.tiragem %></p>
    <p><strong>Selo:</strong> <%= @book.selo %></p>
    <p><strong>Data de Entrega:</strong> <%= @book.delivery_date.strftime('%d/%m/%Y') %></p>
    <p><strong>Fitilho:</strong> <%= @book.fitilho %></p>
    <p><strong>Cabeceado:</strong> <%= @book.cabeceado %></p>
    <p><strong>Pintura Lateral:</strong> <%= @book.pintura_lateral %></p>
    <p><strong>Sticker:</strong> <%= @book.sticker ? 'Sim' : 'Não' %></p>
    <p><strong>Encartes:</strong> <%= @book.encartes ? 'Sim' : 'Não' %></p>

    <h3>Dados de Capa</h3>
    <p><strong>Tipo de Capa:</strong> <%= @book.cover_type %></p>
    <p><strong>Formato de Capa:</strong> <%= @book.cover_format %></p>
    <p><strong>Papel da Capa:</strong> <%= @book.cover_paper %></p>
    <p><strong>Cores da Capa:</strong> <%= @book.cover_colors %></p>
    <p><strong>Acabamento da Capa:</strong> <%= @book.cover_finish %></p>

    <h3>Dados do Miolo</h3>
    <p><strong>Formato do Miolo:</strong> <%= @book.miolo_format %></p>
    <p><strong>Papel do Miolo:</strong> <%= @book.miolo_paper %></p>
    <p><strong>Cores do Miolo:</strong> <%= @book.miolo_colors %></p>
    <p><strong>Acabamento do Miolo:</strong> <%= @book.miolo_finish %></p>

    <h3>Dados de Guarda</h3>
    <p><strong>Formato da Guarda:</strong> <%= @book.guarda_format %></p>
    <p><strong>Papel da Guarda:</strong> <%= @book.guarda_paper %></p>
    <p><strong>Cores da Guarda:</strong> <%= @book.guarda_colors %></p>
    <p><strong>Acabamento da Guarda:</strong> <%= @book.guarda_finish %></p>

    <p style="margin-top: 80px"><%= "Rio de Janeiro, #{Date.today.strftime('%d/%m/%Y')}, #{current_user.name}" %></p>
  </div>
</body>
</html>

app/views/books/all.html.erb
<%= render 'navbar' %>

<h4 class="page-title">TODOS OS TITULOS CADASTRADOS:</h4>

<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-4 mb-4">
        <%= link_to "#{book.code} - #{book.title}", book_path(book.id), style: 'text-decoration: none;', class: 'book-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<%= render 'navbar' %>

<div class= "new-book-container">
  <div class= "book-form-header">
    <%= image_tag('logo_darkside_branca.png', class:'small-logo') %>
   <h2><strong>CHECKLIST DE <%= @book.title.upcase %></strong></h2>
  </div>
  <div class= 'book-form'>
  <%= simple_form_for @book do |f| %>
    <h3>Dados Gerais</h3>

    <%= f.input :title, label: "Título", input_html: { style: "width: 500px;" } %>
    <%= f.input :code, label: "Código", input_html: { style: "width: 500px;" } %>
    <%= f.input :pages, label: "Páginas", input_html: { style: "width: 500px;" } %>
    <%= f.input :tiragem, input_html: { style: "width: 500px;" } %>
    <%= f.input :selo, input_html: { style: "width: 500px;" } %>
    <%= f.input :delivery_date, input_html: { style: "width: 33%;" } %>
    <%= f.input :fitilho, input_html: { style: "width: 500px;" } %>
    <%= f.input :cabeceado, input_html: { style: "width: 500px;" } %>
    <%= f.input :pintura_lateral, input_html: { style: "width: 500px;" } %>
    <%= f.input :sticker %>
    <%= f.input :encartes %>

    <h3>Dados de Capa</h3>

    <%= f.input :cover_type, label: "Tipo de Capa", input_html: { style: "width: 500px;" } %>
    <%= f.input :cover_format, label: "Formato de Capa", input_html: { style: "width: 500px;" } %>
    <%= f.input :cover_paper, label: "Papel da Capa", input_html: { style: "width: 500px;" } %>
    <%= f.input :cover_colors, label: "Cores da Capa", input_html: { style: "width: 500px;" } %>
    <%= f.input :cover_finish, label: "Acabamento da Capa", input_html: { style: "width: 500px;" } %>

    <h3>Dados do Miolo</h3>

    <%= f.input :miolo_format, label: "Formato do Miolo", input_html: { style: "width: 500px;" } %>
    <%= f.input :miolo_paper, label: "Papel do Miolo", input_html: { style: "width: 500px;" } %>
    <%= f.input :miolo_colors, label: "Cores do Miolo", input_html: { style: "width: 500px;" } %>
    <%= f.input :miolo_finish, label: "Acabamento do Miolo", input_html: { style: "width: 500px;" } %>

    <h3>Dados de Guarda</h3>

    <%= f.input :guarda_format, label: "Formato da Guarda", input_html: { style: "width: 500px;" } %>
    <%= f.input :guarda_paper, label: "Papel da Guarda", input_html: { style: "width: 500px;" } %>
    <%= f.input :guarda_colors, label: "Cores da Guarda", input_html: { style: "width: 500px;" } %>
    <%= f.input :guarda_finish, label: "Acabamento da Guarda", input_html: { style: "width: 500px;" } %>

    </div>

    <div class="container book-form">
      <h3>Orçamento:</h3>

      <% if @book.printing_prices.all? { |price| price.quantity.present? || price.ipsis_price.present? || price.coan_price.present? || price.geografica_price.present? || price.leograf_price.present? || price.santa_marta_price.present? || prince.pancron_price.present? } %>
        <table class = "table">
          <thead>
            <tr>
              <th>Quantity</th>
              <th>Ipsis Price</th>
              <th>Coan Price</th>
              <th>Geografica Price</th>
              <th>Leograf Price</th>
              <th>Santa Marta Price</th>
              <th>Pancron Price</th>
            </tr>
          </thead>
          <tbody>
            <% grouped_prices = @book.printing_prices.group_by(&:quantity) %>
            <% grouped_prices.each do |quantity, prices| %>
              <tr>
                <td style="text-align: center; vertical-align: middle;">
                  <div >
                    <strong><%= quantity %></strong>
                    </div>
                </td>
                <% prices.each do |price| %>
                   <td>
                    <div id = "input-mb-0">
                      <%= f.simple_fields_for :printing_prices, price do |ff| %>
                        <%= ff.input :ipsis_price, label: false %>
                      <% end %>
                    </div>
                  </td>
                  <td>
                    <%= f.simple_fields_for :printing_prices, price do |ff| %>
                      <%= ff.input :coan_price, label: false %>
                    <% end %>
                  </td>
                  <td>
                    <%= f.simple_fields_for :printing_prices, price do |ff| %>
                      <%= ff.input :geografica_price, label: false %>
                    <% end %>
                  </td>
                  <td>
                    <%= f.simple_fields_for :printing_prices, price do |ff| %>
                      <%= ff.input :leograf_price, label: false %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
        <% else %>
          <table class="table table-responsive">
            <thead>
              <tr>
                <th>Quantity</th>
                <th>Ipsis Price</th>
                <th>Coan Price</th>
                <th>Geografica Price</th>
                <th>Leograf Price</th>
                <th>Santa Marta Price</th>
                <th>Pancron Price</th>
              </tr>
            </thead>
              <tbody>
                <% 4.times do %>
                <div>
                 <tr>
                    <%= f.simple_fields_for :printing_prices do |ff| %>
                      <td><%= ff.input :quantity, label: false %></td>
                      <td><%= ff.input :ipsis_price, label: false, placeholder: "R$" %></td>
                      <td><%= ff.input :coan_price, label: false, placeholder: "R$" %></td>
                      <td><%= ff.input :geografica_price, label: false, placeholder: "R$" %></td>
                      <td><%= ff.input :leograf_price, label: false, placeholder: "R$", inputmode: "numeric" %></td>
                      <td><%= ff.input :santa_marta_price, label: false, placeholder: "R$" %></td>
                      <td><%= ff.input :pancron_price, label: false, placeholder: "R$" %></td>
                    <% end %>
                  </tr>
                </div>
                <% end %>
              </tbody>
          <% end %>
          </table>
            <%= f.submit "Atualizar Check-list", class: "btn btn-dark mt-5"; %>
      <% end %>
    </div>
</div>


<script>
  var elements = document.querySelectorAll("div.decimal.optional");

  console.log(elements)

  for (var element of elements) {
    element.classList.remove("mb-3");
  }

    </script>

app/views/books/index.html.erb
<%= render 'navbar' %>

<div class="container">
  <div class="row">
    <!-- Menu Acordeão -->
    <div class="col-md-3 ">
      <div class="side-bar-menu">
        <h4 id='menu-title'>Menu</h4>
        <div class="accordion" id="verticalAccordion">
          <div class="accordion-item">
            <h3 class="accordion-header" id="headingOne">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Checklist
              </button>
            </h3>
            <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#verticalAccordion">
              <ul class="list-unstyled">
                <li><%= link_to 'Cadastrar', new_book_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Ver Todas', all_books_path, class: 'dropdown-item' %></li>
              </ul>
            </div>
          </div>
          <div class="accordion-item">
            <h3 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Kit Book
              </button>
            </h3>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#verticalAccordion">
              <ul class="list-unstyled">
                <li><%= link_to 'Cadastrar', new_kit_book_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Todos/Buscar', kit_books_path, class: 'dropdown-item' %></li>
              </ul>
            </div>
          </div>
          <div class="accordion-item">
            <h3 class="accordion-header" id="headingThree">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Orçamento Livros
              </button>
            </h3>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#verticalAccordion">
              <ul class="list-unstyled">
                <li><%= link_to 'Ver Todos', printing_prices_index_books_path(@book), class: 'dropdown-item' %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
   </div>



<div class="col-md-9">
  <div class="index-content">
      <h2 style="margin-bottom: 40px"> Busque por um título</h2>

      <div class="row justify-content-center">
        <div class="col-md-9">
          <%= form_with url: books_path, method: :get, class: "d-flex" do %>
            <div class="input-group">
              <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "Digite o título ou código do livro"
                %>
              <div class="input-group-append">
                <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <% if params[:query].present? %>
        <% if @books.any? %>
          <% @books.each do |book| %>
            <h3>Resultado da Pesquisa:</h3>
            <%= link_to "#{book.code} - #{book.title}", book_path(book.id), style: 'text-decoration: none;', class: 'book-button' %>
          <% end %>
        <% else %>
          <p id="search-no-result">Nenhum resultado encontrado.</p>
        <% end %>
      <% end %>

      <div class="all-books">
        <%= link_to "Ver todos os Checklists", all_books_path, class: "btn btn-secondary" %>
        <li><%= link_to 'Cadastrar um Checklist', new_book_path, class: "btn btn-success"%></li>
      </div>
  </div>
</div>

</div>

<script>
  $('.dropdown-toggle').click(function() {
    $(this).next('.dropdown-menu').toggle();
  });
</script>

app/views/books/printing_prices_index.html.erb
<%= render 'navbar' %>

<h4 class="page-title">SELECIONE O TITULO QUE DESEJA VER O ORÇAMENTO:</h4>

<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-4 mb-4">
         <%= link_to "#{book.code} - #{book.title}", printing_prices_show_book_path(book.id), style: 'text-decoration: none; align-self: center', class: 'book-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/printing_prices_show.html.erb
<%= render "navbar" %>

<div class="container mt-5">
  <h4 class="mt-4" style="text-align: center">Orçamento do Livro <%= @book.title %></h4>

  <div class="table-responsive">
    <table class="table table-auto">
      <thead>
        <tr>
          <th>Quantidade</th>
          <th>Preço Ipsis</th>
          <th>Preço Coan</th>
          <th>Preço Geográfica</th>
          <th>Preço Leográfica</th>
        </tr>
      </thead>
      <tbody>
        <% @book.printing_prices.each do |price| %>
          <tr>
            <td><%= price.quantity %></td>
            <td>R$ <%= number_with_precision(price.ipsis_price, precision: 2, separator: ',', delimiter: '.') %></td>
            <td>R$ <%= number_with_precision(price.coan_price, precision: 2, separator: ',', delimiter: '.') %></td>
            <td>R$ <%= number_with_precision(price.geografica_price, precision: 2, separator: ',', delimiter: '.') %></td>
            <td>R$ <%= number_with_precision(price.leograf_price, precision: 2, separator: ',', delimiter: '.') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <button class="btn btn btn-outline-dark mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#dadosGerais" aria-expanded="false" aria-controls="dadosGerais">
  Dados Gerais
  </button>

  <div class="table-responsive">
    <div class="collapse" id="dadosGerais">
      <table class="table">
        <thead>
          <tr>
            <th>Título</th>
            <th>Código</th>
            <th>Páginas</th>
            <th>Tiragem</th>
            <th>Selo</th>
            <th>Data de Entrega</th>
            <th>Fitilho</th>
            <th>Cabeceado</th>
            <th>Pintura Lateral</th>
            <th>Adesivo</th>
            <th>Encartes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @book.title %></td>
            <td><%= @book.code %></td>
            <td><%= @book.pages %></td>
            <td><%= @book.tiragem %></td>
            <td><%= @book.selo %></td>
            <td><%= @book.delivery_date %></td>
            <td><%= @book.fitilho %></td>
            <td><%= @book.cabeceado %></td>
            <td><%= @book.pintura_lateral %></td>
            <td><%= @book.sticker %></td>
            <td><%= @book.encartes %></td>
          </tr>
        </tbody>
      </table>
    </div >
  </div>


  <button class="btn btn btn-outline-dark mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#dadosCapa" aria-expanded="false" aria-controls="dadosCapa">
  Dados de Capa
  </button>
  <div class="table-responsive">
    <div class="collapse" id="dadosCapa">
      <table class="table">
        <thead>
          <tr>
            <th>Tipo de Capa</th>
            <th>Formato da Capa</th>
            <th>Papel da Capa</th>
            <th>Cores da Capa</th>
            <th>Acabamento da Capa</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @book.cover_type %></td>
            <td><%= @book.cover_format %></td>
            <td><%= @book.cover_paper %></td>
            <td><%= @book.cover_colors %></td>
            <td><%= @book.cover_finish %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

 <button class="btn btn btn-outline-dark mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#dadosMiolo" aria-expanded="false" aria-controls="dadosMiolo">
    Dados do Miolo
 </button>

  <div class="table-responsive">
    <div class="collapse" id="dadosMiolo">
      <table class="table">
        <thead>
          <tr>
            <th>Formato do Miolo</th>
            <th>Papel do Miolo</th>
            <th>Cores do Miolo</th>
            <th>Acabamento do Miolo</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @book.miolo_format %></td>
            <td><%= @book.miolo_paper %></td>
            <td><%= @book.miolo_colors %></td>
            <td><%= @book.miolo_finish %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>


 <button class="btn btn btn-outline-dark mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#dadosGuarda" aria-expanded="false" aria-controls="dadosGuarda">
    Dados da Guarda
 </button>

  <div class="table-responsive">
    <div class="collapse" id="dadosGuarda">
      <table class="table">
        <thead>
          <tr>
            <th>Formato da Guarda</th>
            <th>Papel da Guarda</th>
            <th>Cores da Guarda</th>
            <th>Acabamento da Guarda</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @book.guarda_format %></td>
            <td><%= @book.guarda_paper %></td>
            <td><%= @book.guarda_colors %></td>
            <td><%= @book.guarda_finish %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

    <%= link_to 'Editar', edit_book_path(@book), class: "btn btn-dark" %>

</div>

app/views/books/show.html.erb
<%= render 'navbar' %>

<div class= "book-form-header">
   <%= image_tag('logo_darkside_branca.png', class:'small-logo') %>
  <h2><strong>CHECKLIST DE LANÇAMENTO</strong></h2>
</div>

<div class= 'show-form'>
  <h4>Dados Gerais</h4>
  <p><strong>Título:</strong> <%= @book.title %></p>
  <p><strong>Código:</strong> <%= @book.code %></p>
  <p><strong>Páginas:</strong> <%= @book.pages %></p>
  <p><strong>Tiragem:</strong> <%= @book.tiragem %></p>
  <p><strong>Selo:</strong> <%= @book.selo %></p>
  <p><strong>Data de Entrega:</strong> <%= @book.delivery_date %></p>
  <p><strong>Fitilho:</strong> <%= @book.fitilho %></p>
  <p><strong>Cabeceado:</strong> <%= @book.cabeceado %></p>
  <p><strong>Pintura Lateral:</strong> <%= @book.pintura_lateral %></p>
  <p><strong>Sticker:</strong> <%= @book.sticker ? 'Sim' : 'Não' %></p>
  <p><strong>Encartes:</strong> <%= @book.encartes ? 'Sim' : 'Não' %></p>

  <h4>Dados de Capa</h4>
  <p><strong>Tipo de Capa:</strong> <%= @book.cover_type %></p>
  <p><strong>Formato de Capa:</strong> <%= @book.cover_format %></p>
  <p><strong>Papel da Capa:</strong> <%= @book.cover_paper %></p>
  <p><strong>Cores da Capa:</strong> <%= @book.cover_colors %></p>
  <p><strong>Acabamento da Capa:</strong> <%= @book.cover_finish %></p>

  <h4>Dados do Miolo</h4>
  <p><strong>Formato do Miolo:</strong> <%= @book.miolo_format %></p>
  <p><strong>Papel do Miolo:</strong> <%= @book.miolo_paper %></p>
  <p><strong>Cores do Miolo:</strong> <%= @book.miolo_colors %></p>
  <p><strong>Acabamento do Miolo:</strong> <%= @book.miolo_finish %></p>

  <h4>Dados de Guarda</h4>
  <p><strong>Formato da Guarda:</strong> <%= @book.guarda_format %></p>
  <p><strong>Papel da Guarda:</strong> <%= @book.guarda_paper %></p>
  <p><strong>Cores da Guarda:</strong> <%= @book.guarda_colors %></p>
  <p><strong>Acabamento da Guarda:</strong> <%= @book.guarda_finish %></p>
</div>


<div class="show-footer">
  <%= link_to "Gerar PDF", show_pdf_book_path(@book, format: :pdf), class: "btn btn-success" %>
  <div class="buttons-show-footer">
    <%= link_to 'Editar', edit_book_path(@book), class: "btn btn-dark" %>
      <%= link_to 'Deletar', book_path(@book), data: {turbo_method: :delete, turbo_confirm: "Tem certeza que quer deletar a checklist?"}, class: "btn btn-danger" %>
      <%= link_to 'Voltar', books_path,  class: "btn btn-dark" %>
    </div>
  </div>

app/views/books/show.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>CHECKLIST</title>
  <!-- Inclua os cabeçalhos e estilos necessários para a formatação do PDF aqui -->
</head>
<body>
  <%= render 'books/show' %>
</body>
</html>