config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'books#index'

  resources :books do
    resources :printing_prices, shallow: true
    member do
      get 'show_pdf', format: :pdf
      get 'printing_prices_show', to: 'books#printing_prices_show', as: 'printing_prices_show'
    end
    collection do
      get 'printing_prices_index', to: 'books#printing_prices_index', as: 'printing_prices_index'
      get 'all', to: 'books#all', as: 'all'
    end
  end


  resources :kit_books do
    resources :items
  end
   # Registrar o controller search
   resources :search, controller: 'search', stimulus: './search_controller'
end

app/models/kit_book.rb
class KitBook < ApplicationRecord
  belongs_to :book
  has_many :items, dependent: :destroy
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
end

app/controllers/kit_books_controller.rb
class KitBooksController < ApplicationController
  before_action :set_kit_book, only: [:show, :edit, :update, :destroy]

  def index
    @kit_books = KitBook.all
  end

  def show
    items_price = []

    # Certifique-se de que @kit_book e @kit_book.items estejam definidos corretamente

    # Iterar pelos itens do kit e calcular a soma dos preços
    @kit_book.items.each do |item|
      items_price << item.total_price
    end

    # Calcular o preço total e atribuí-lo a @kit_book.total_price
    @kit_book.total_price = items_price.sum
    # raise
  end

  def new
    @kit_book = KitBook.new
    5.times { @kit_book.items.build } # Construir 2 itens iniciais
    @item_number = 1

    # Remove the empty div from the DOM
    if @kit_book.items.count == 1
      @kit_book.items[0].destroy
    end
  end

  def create
    @kit_book = KitBook.new(kit_book_params)
    @kit_book.name = Book.find(kit_book_params[:book_id]).title if kit_book_params[:book_id].present?
    puts "Params received: #{params.inspect}" # Debugging output

    if @kit_book.save
      redirect_to @kit_book, notice: 'Kit Book criado com sucesso.'
    else
      puts "Validation Errors: #{@kit_book.errors.full_messages}"
        # render :new
    end
  end


  def edit
    # Editar o kit de livros
    @kit_book = KitBook.find(params[:id])
    @item_number = 1

    # Remove the empty div from the DOM
    if @kit_book.items.count == 1
       @kit_book.items[0].destroy
    end
  end

  def update
    @item_number = 1
    if @kit_book.update(kit_book_params)
      redirect_to @kit_book, notice: 'Kit de livros atualizado com sucesso.'
    else
      errors = @kit_book.errors.full_messages.join(', ')
      puts errors
      Rails.logger.error("Erro ao atualizar KitBook: #{@kit_book.errors}")
      puts "Erro ao atualizar KitBook: #{@kit_book.errors}"
      render :edit
    end
  end

  def destroy
    @kit_book.destroy
    redirect_to kit_books_url, notice: 'Kit de livros excluído com sucesso.'
  end

  private

  def set_kit_book
    @kit_book = KitBook.find(params[:id])
  end

  def kit_book_params
    params.require(:kit_book).permit(:book_id, :budget_price, :name, items_attributes: [:id, :item, :quantity, :supplier, :unit_price, :total_price, :shipping, :observation, :_destroy])
  end

end

app/helpers/kit_books_helper.rb
module KitBooksHelper
end

app/views/kit_books/_item_fields.html.erb
<!-- app/views/kit_books/_item_fields.html.erb -->
<div class="nested-fields">
  <%= f.input :item, label:"Nome do Item" %>
  <%= f.input :quantity, label: "Quantidade" %>
  <%= f.input :supplier, label: "Fornecedor" %>
  <%= f.input :total_price , label: "Valor Total"  %>
  <%= f.input :shipping,  label: "Frete" %>
  <%= f.input :observation, label: "Observações" %>
  <%= link_to_remove_association "Remove Item", f, class: "btn btn-danger" %>
</div>

app/views/kit_books/_item_fields_edit.html.erb
<!-- app/views/kit_books/_item_fields.html.erb -->
<div class="nested-fields">
<% @kit_book.item_ids.each_with_index do |id, index| %>
  <h5>Item <%= index + 1 %></h5>
  <%= f.input :item, label: "Nome do Item" %>
  <%= f.input :quantity, label: "Quantidade" %>
  <%= f.input :supplier, label: "Fornecedor" %>
  <%= f.input :total_price, label: "Valor Total" %>
  <%= f.input :shipping, label: "Frete" %>
  <%= f.input :observation, label: "Observações" %>
  <%= link_to_remove_association "Remove Item", f, class: "btn btn-danger" %>
<% end %>
</div>

app/views/kit_books/_navbar.html.erb
<nav>
  <ul class='app-header'>
    <div class="nav=-logo">
    <li><%= link_to image_tag('logo_darkside.jpg', class:'logo-navbar', alt:'logo da darkside em extenso vermelho'), root_path %>
      </li>
    </div>


<% if user_signed_in? %>
<div class="accordion accordion-stay-open" id="verticalAccordion">
  <div class="accordion-item">
    <h3 class="accordion-header" id="headingUser">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseUser" aria-expanded="true" aria-controls="collapseUser" class="collapse-disabled">
        <%= current_user.name %>
      </button>
    </h3>
      <div id="collapseUser" class="accordion-collapse collapse" aria-labelledby="headingUser" data-bs-parent="#verticalAccordion">
        <ul class="list-unstyled py-2">
          <li class="pb-2"><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, style: "padding: 0.25rem 1rem;", id: 'id="nav-list-item' %></li>
          <li><%= link_to "Editar Usuário", edit_user_registration_path, style: 'padding: 0.25rem 1rem;' %></li>
        </ul>
      </div>
    <% else %>
      <div class="accordion-item">
        <h3 class="accordion-header" id="headingLogin">
          <button class="accordion-button collapse" type="button" data-bs-toggle="collapse" data-bs-target="#collapseLogin" aria-expanded="true" aria-controls="collapseLogin">
            Menu de Login
          </button>
        </h3>
        <div id="collapseLogin" class="accordion-collapse collapse" aria-labelledby="headingLogin" data-bs-parent="#verticalAccordion">
          <ul class="list-unstyled">
            <li><%= link_to "Cadastre-se", new_user_registration_path, style: 'text-decoration: none; color: black;' %></li>
            <li><%= link_to "Login", new_user_session_path, style: 'text-decoration: none; color: black;' %></li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>


      </ul>
    </li>
  </ul>
</nav>

app/views/kit_books/edit.html.erb
<%= render 'navbar' %>

<div class="new-book-container">
  <div class="book-form-header">
    <%= image_tag('logo-dark-preta.png', class: 'avatar-large') %>
    <h2><strong>Editar KitBook</strong></h2>
  </div>
  <div class='book-form'>
    <%= simple_form_for @kit_book do |f| %>
      <!-- KitBook fields -->
      <div class="d-flex flex-column justify-content-around p-2">
        <h3 style="text-align: start">Nome do Kit Book: <%= f.collection_select :book_id, Book.all, :id, :title, { prompt: "Selecione um livro", selected: @kit_book.book_id }, { style: 'font-size: 22px' } %></h3>

        <h5>Orçamento R$: <%= f.select :budget_price, [[number_with_precision(1500, precision: 2, separator: ',', delimiter: '.'), 1500], [number_with_precision(2500, precision: 2, separator: ',', delimiter: '.'), 2500], [number_with_precision(5000, precision: 2, separator: ',', delimiter: '.'), 5000]], {},{ style: 'font-size: 16px; align-self: end;'  } %></h5>
      </div>

      <!-- Item fields -->
      <div id="item-fields" class="item-flex-container">

            <%= f.simple_fields_for :items do |item_fields| %>
          <div>
            <%= render 'item_fields', f: item_fields %>
          </div>
          <% end %>
        <div class="links item-flex mt-auto">
          <%= link_to_add_association 'Adicionar Item', f, :items, class: "btn btn-primary" %>
        </div>
      </div>
      <%= f.submit "Atualizar Kit Book", class: "btn btn-dark mt-5"; %>
    <% end %>
  </div>
</div>

app/views/kit_books/index.html.erb
<%= render 'navbar' %>


<h4 class="page-title">TODOS OS KIT BOOKS CADASTRADOS:</h4>

<div class="container">
  <div class="row">
    <% @kit_books.each do |kit_book| %>
        <div class="col-md-4 mb-4">
          <%= link_to "Kit Boook - #{kit_book.name}", kit_book_path(kit_book.id), style: 'text-decoration: none; align-self: center', class: 'book-button' %>
        </div>
     <% end %>
  </div>
</div>

app/views/kit_books/new.html.erb
<%= render 'navbar' %>

<div class="new-book-container">
  <div class="book-form-header">
    <%= image_tag('logo_darkside_branca.png', class: 'small-logo') %>
    <h2><strong>Cadastrar KitBook</strong></h2>
  </div>
  <div class='book-form'>
    <%= simple_form_for @kit_book do |f| %>
      <!-- KitBook fields -->
      <div class="d-flex justify-content-around p-2 mb-4">
        <h4>Nome do Kit Book: <%= f.collection_select :book_id, Book.all, :id, :title, { prompt: "Selecione um livro", selected: @kit_book.book_id }, { style: 'font-size: 16px' } %></h4>
        <h5>Orçamento R$: <%= f.select :budget_price, [[number_with_precision(1500, precision: 2, separator: ',', delimiter: '.'), 1500], [number_with_precision(2500, precision: 2, separator: ',', delimiter: '.'), 2500], [number_with_precision(5000, precision: 2, separator: ',', delimiter: '.'), 5000]], {},{ style: 'font-size: 16px; align-self: end' } %></h5>
      </div>
      <!-- Item fields -->
      <div id="item-fields" class="item-flex-container">
          <%= f.simple_fields_for :items do |item_fields| %>
            <div>
              <%= render 'item_fields', f: item_fields %>
            </div>
          <% end %>
        <div class="links item-flex">
          <%= link_to_add_association 'Adicionar Item', f, :items, class: "btn btn-primary" %>
        </div>
      </div>

      <%= f.submit "Cadastrar Kit Book", class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/kit_books/show.html.erb
<%= render "navbar" %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class= "book-form-header">
   <%= image_tag('logo_darkside_branca.png', class:'small-logo') %>
  <h2><strong>ORÇAMENTO DO KITBOOK <%= link_to @kit_book.name.upcase, book_path %></strong></h2>
 </div>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Item</th>
        <th>Quantidade</th>
        <th>Fornecedor</th>
        <th>Preço Unitário</th>
        <th>Preço Total</th>
        <th>Frete</th>
        <th>Observações</th>

      </tr>
    </thead>
    <tbody>
      <% @kit_book.items.each do |item| %>
        <tr>
          <td><%= item.item %></td>
          <td><%= item.quantity %></td>
          <td><%= item.supplier %></td>
          <td>R$ <%= number_with_precision(item.unit_price, precision: 2, separator: ',', delimiter: '.') %></td>
          <td>R$ <%= number_with_precision(item.total_price, precision: 2, separator: ',', delimiter: '.') %></td>
          <td>R$ <%= number_with_precision(item.shipping, precision: 2, separator: ',', delimiter: '.') %></td>
          <td><%= item.observation %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="kit-book-footer">
    <%= link_to "Editar Kit Book", edit_kit_book_path, class:"btn btn-dark", style:"height: 40px;"  %>
    <table>
  <thead>
    <tr>
      <th style="margin: 0">
        <strong>Orçamento:</strong>
      </th>
    </tr>
  <thead>
  <tbody>
    <tr>
      <td style="margin: 0">
        <% if @kit_book.budget_price.is_a?(String) %>
         <strong>R$ <%= number_with_precision(@kit_book.budget_price, precision: 2, separator: ',', delimiter: '.') %></strong>
        <% else %>
          <strong>O Valor do Orçamento ainda não foi definido</strong>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>


    <table>
      <thead>
        <tr>
          <th><strong>Total do Kit:</strong></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% if @kit_book.total_price.present? %>
              <td><strong>R$ <%= number_with_precision(@kit_book.total_price, precision: 2, separator: ',', delimiter: '.')%></strong></td>
          <% else %>
              <td><strong>O Valor do Orçamento ainda não foi definido</strong></td>
          <% end %>

        </tr>
      </tbody>
    </table>
  </div>
</div>